### ISSUE TITLE
Spawn error after packaging

### ISSUE THREAD

**Issue by X-Raym** [joshwnj/ffprobe-static#5]
Hi,

Just after compilation with electron-builder,  
I get this error in my app from ffprobe-static

```
Uncaught Error: spawn C:\Users\Anymord\AppData\Local\Temp\nsuFBDD.tmp\app\resources\app.asar\node_modules\ffprobe-static\bin\win32\x64\ffprobe.exe ENOENT
    at exports._errnoException (util.js:1022)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193)
    at onErrorNT (internal/child_process.js:359)
    at _combinedTickCallback (internal/process/next_tick.js:74)
    at process._tickCallback (internal/process/next_tick.js:98)
```
Here is my setup :
From my package.json

```
  "dependencies": {
   ...
    "ffprobe": "^1.1.0",
    "ffprobe-static": "^2.0.0",
...
}
```

In a script called by index.html
```
const ffprobe = require('ffprobe')
const ffprobeStatic = require('ffprobe-static')
```

and the call 
```
    ffprobe(item.filePath, {
      path: ffprobeStatic.path
    }, function (err, info) { 
```

What did I missed ?

Thanks for your support !

**Comment by develar** [comment]
It is electron-builder misconfiguration issue. I will answer you in the Slack.

**Comment by X-Raym** [comment]
It was indeed, electron-builder misconfiguration.

Here what I end up with, thanks to @develar !

``` JSON
  "build": {
    "files": "!node_modules/ffprobe-static/**/*",
    "mac": {
      "target": "dmg",
      "extraResources": {
        "from": "node_modules/ffprobe-static/bin/darwin/x64"
      }
    },
    "win": {
      "target": "portable",
      "extraResources": {
        "from": "node_modules/ffprobe-static/bin/win32/x64"
      }
    }
  }
```

And in JavaScript file:

```JavaScript
var ffprobeStaticPath = ''
if (!__dirname.includes('.asar')) { // If dev
  ffprobeStaticPath = require('ffprobe-static').path
} else { // if compiled
  let ext = ''
  if (process.platform === 'win32') ext = '.exe' // if windows
  ffprobeStaticPath = path.join(process.resourcesPath + '/ffprobe' + ext)
}
```

This allows to:

- Only pack binary needed for a chosen distribution
- Have a valid path to ffprobe
- Have no change for non packed version

Many thanks to @develar for its precious help !

**Comment by joshwnj** [comment]
thanks @X-Raym and @develar

**Comment by preciousome** [comment]
what if i have both ffprobe and ffmpeg-static how do i do that

**Comment by Manjioko** [comment]
thank you so much, I solved my problem @X-Raym

**Comment by NingerJohn** [comment]
Got same error even while I try to use npm to run electron serve, not packaging.
And above solution not working for me

**Comment by NingerJohn** [comment]
What about the error in electron during development?
I got the same issue while I run `npm run electron:serve`, which is map to `vue-cli-service electron:serve`

**Comment by NordlingDev** [comment]
I had the exact same problem. The solution @X-Raym mentions did inspire another fix for me. First of all, it's not clear for some (including me) that `child_process.spawn` can't spawn processes inside `app.asar` archives. That's why we have to redirect those paths into the `app.asar.unpacked` directory which lies directly next to `app.asar` (this might work differently depending on packaging tools, but I'm using electron-builder to package my build).

Here's is the final solution that I went for:

```ts
// ffmpeg.ts - This is a custom file that I have inside my project that re-exports ffmpeg after setting the paths
import ffmpeg from "fluent-ffmpeg";
import ffmpegPath from "ffmpeg-static";
import { path as ffprobePath } from "ffprobe-static";
import electronIsDev from "electron-is-dev";

const paths = {
    ffmpeg: ffmpegPath,
    ffprobe: ffprobePath,
};

if (!electronIsDev) {
    const fixPath = (path: string) => path.replace("app.asar", "app.asar.unpacked");
    paths.ffmpeg = fixPath(paths.ffmpeg);
    paths.ffprobe = fixPath(paths.ffprobe);
}

ffmpeg.setFfmpegPath(paths.ffmpeg);
ffmpeg.setFfprobePath(paths.ffprobe);

export { ffmpeg };
```
