### ISSUE TITLE
Upgrade to ffprobe 4.0?

### ISSUE THREAD

**Issue by philipjscott** [joshwnj/ffprobe-static#7]
I get a segmentation fault when I try to pass a URL to `ffprobe` version 3.1 (the binary installed by `ffprobe-static`). Everything seems to work fine with my local binary, which is version 4.0.

If you're fine with bumping the version, I'll make a PR :smile:

**Comment by keylase** [comment]
Of course - it's simple :zap:  i'll do it :smile:

**Comment by Maxou44** [comment]
I created a Pull Request #8  😊

**Comment by joshwnj** [comment]
published to npm @ `3.0.0`

**Comment by joshwnj** [comment]
hmm actually `npm publish` is timing out so you won't find it there just yet :) I'll update again when it's ready.

**Comment by joshwnj** [comment]
Done https://www.npmjs.com/package/ffprobe-static/v/3.0.0
